spring.application.name=sales-management-software
spring.datasource.url=jdbc:mysql://localhost:3306/SMS_DB?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456


spring.jpa.hibernate.ddl-auto=validate